name: oci_mirror_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - click
  - requests
  - oras-py=0.1.14
  - conda-package-handling
  - zstandard
  - packaging
  - pre-commit
  - pytest
  - pytest-xprocess
