name: Release

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*
  pull_request:

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@ba3bb36eb2066252b2363392b7739741bb777659 # v0.8.1

      - name: Build
        run: pixi run python -m build --no-isolation .

      - name: Check build
        run: pixi run twine check dist/*

      - name: Upload package
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4
        with:
          name: artifact
          path: dist/*

  release:
    name: Publish Package
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    environment: pypi
    steps:
      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        with:
          name: artifact
          path: dist
      - name: Publish package on TestPyPi
        uses: pypa/gh-action-pypi-publish@0ab0b79471669eb3a4d647e625009c62f9f3b241 # v1.10.1
        with:
          repository-url: https://test.pypi.org/legacy/
      - name: Publish package on PyPi
        uses: pypa/gh-action-pypi-publish@0ab0b79471669eb3a4d647e625009c62f9f3b241 # v1.10.1
