name: conda-mirror test

permissions:
  contents: read

on:
  pull_request: null

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v3
      - uses: prefix-dev/setup-pixi@d3f436a425481402e6a95a1d1fc10331c708cd9e # v0.10.2
        with:
          pixi-version: v0.81.0
          environments: lint
      - name: Lint Conda Oci Mirror
        run: pixi run lint

  testing:
    runs-on: ubuntu-latest
    services:
      registry:
        image: ghcr.io/oras-project/registry:latest
        env:
          REGISTRY_STORAGE_DELETE_ENABLED: "true"
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v3
      - uses: prefix-dev/setup-pixi@d3f436a425481402e6a95a1d1fc10331c708cd9e # v0.10.2
        with:
          pixi-version: v0.81.0
      - name: Test Conda OCI Mirror
        env:
          registry_host: http://localhost
          registry_port: ${{ job.services.registry.ports[5000] }}
        run: pixi run test

  mirror-pkgs:
    runs-on: ubuntu-latest
    services:
      registry:
        image: ghcr.io/oras-project/registry:latest
        env:
          REGISTRY_STORAGE_DELETE_ENABLED: "true"
        ports:
          - 5000:5000
    strategy:
      max-parallel: 12
      matrix:
        package: [redo]
        subdir:
          - linux-64
          - osx-64
          - osx-arm64
          - win-64
          - linux-aarch64
          - linux-ppc64le
          - noarch
      fail-fast: true
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v3
      - uses: prefix-dev/setup-pixi@d3f436a425481402e6a95a1d1fc10331c708cd9e # v0.10.2
        with:
          pixi-version: v0.81.0

      - name: Test Conda Oci Mirror
        shell: pixi run bash -e {0}
        env:
          channel: conda-forge
          subdir: ${{ matrix.subdir }}
          package: ${{ matrix.package }}
          registry_host: localhost
          registry_port: ${{ job.services.registry.ports[5000] }}
        run: |
          export PYTHONUNBUFFERED=1

          # First run mirror
          conda-oci mirror --channel ${channel} --subdir ${subdir} --package ${package} --registry http://${registry_host}:${registry_port}/dinosaur

          # Then run pull-cache and push-cache
          conda-oci pull-cache --registry http://${registry_host}:${registry_port}/dinosaur --subdir ${subdir} --package ${package}
          conda-oci push-cache --registry http://${registry_host}:${registry_port}/dinosaur --subdir ${subdir} --package ${package}

      - name: View Cache
        run: sudo apt-get install -y tree && tree ./cache
